export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    ME: '/auth/me',
  },
  ADMIN_USERS: '/admin/users',
  ROLES: '/roles',
  BRANCHES: '/branches',
  EMPLOYEES: '/employees',
  CUSTOMERS: '/customers',
  VEHICLES: '/vehicles',
  BRANDS: '/brands',
  APPOINTMENTS: '/appointments',
  RECEPTIONS: '/reception',
  REPAIR_ORDERS: '/repair-orders',
  PARTS: '/parts',
  INVENTORY: '/inventory',
  QUOTATIONS: '/quotations',
  INVOICES: '/invoices',
  NOTIFICATIONS: '/notifications',
  CHAT: '/chat',
  REPORTS: {
    DASHBOARD: '/reports/dashboard',
    REVENUE: '/reports/revenue',
    APPOINTMENTS: '/reports/appointments',
    REPAIR_ORDERS: '/reports/repair-orders',
    SERVICES: '/reports/services',
    PARTS: '/reports/parts',
    INVENTORY: '/reports/inventory',
    TECHNICIANS: '/reports/technicians',
    BRANCHES: '/reports/branches',
  },
} as const;
