SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.HinhAnhXe', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HinhAnhXe (
        MaHinhAnhXe INT IDENTITY(1,1) PRIMARY KEY,
        MaXe INT NOT NULL UNIQUE,
        DuongDanAnh NVARCHAR(500) NOT NULL,
        TenTepGoc NVARCHAR(255) NOT NULL,
        LoaiNoiDung VARCHAR(100) NOT NULL,
        KichThuoc BIGINT NOT NULL,
        NgayCapNhat DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_HinhAnhXe_Xe FOREIGN KEY (MaXe)
            REFERENCES dbo.Xe(MaXe) ON DELETE CASCADE
    );
END;
